import { writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import type { ReportRenderer, ReportData } from './types.js';
import type { FileSystemStorage } from '../../../storage/filesystem.js';

export class MarkdownRenderer implements ReportRenderer {
  name = 'markdown';
  format = 'md';

  async render(data: ReportData, storage: FileSystemStorage): Promise<string> {
    const { analysis, brand } = data;
    const s = analysis.summary;

    let md = `# GEO Analysis Report: ${brand.name}\n\n`;
    md += `> Generated: ${data.generatedAt}\n`;
    md += `> Run ID: ${data.runId}\n\n`;

    // Summary
    md += `## Executive Summary\n\n`;
    md += `**${s.headline}**\n\n`;
    md += `### Key Findings\n\n`;
    for (const finding of s.keyFindings) {
      md += `- ${finding}\n`;
    }

    if (s.strengths.length > 0) {
      md += `\n### Strengths\n\n`;
      for (const str of s.strengths) {
        md += `- ${str}\n`;
      }
    }

    if (s.weaknesses.length > 0) {
      md += `\n### Weaknesses\n\n`;
      for (const w of s.weaknesses) {
        md += `- ${w}\n`;
      }
    }

    if (s.recommendations.length > 0) {
      md += `\n### Recommendations\n\n`;
      for (const r of s.recommendations) {
        md += `- ${r}\n`;
      }
    }

    // Mention Rate
    if (analysis.mentionRate) {
      md += `\n## Mention Rate\n\n`;
      md += `Overall: **${analysis.mentionRate.overall}%** (${analysis.mentionRate.totalMentions}/${analysis.mentionRate.totalResponses})\n\n`;
      md += `| Provider | Mention Rate |\n|----------|-------------|\n`;
      for (const [provider, rate] of Object.entries(analysis.mentionRate.byProvider)) {
        md += `| ${provider} | ${rate}% |\n`;
      }
    }

    // Mindshare
    if (analysis.mindshare) {
      md += `\n## Mindshare\n\n`;
      md += `Overall: **${analysis.mindshare.overall}%** (Rank #${analysis.mindshare.rank})\n\n`;
      md += `| Provider | Mindshare |\n|----------|-----------|\n`;
      for (const [provider, share] of Object.entries(analysis.mindshare.byProvider)) {
        md += `| ${provider} | ${share}% |\n`;
      }
    }

    // Sentiment
    if (analysis.sentiment) {
      md += `\n## Sentiment\n\n`;
      md += `Overall: **${analysis.sentiment.label}** (${analysis.sentiment.overall.toFixed(3)})\n\n`;
      md += `- Positive: ${analysis.sentiment.positiveCount}\n`;
      md += `- Neutral: ${analysis.sentiment.neutralCount}\n`;
      md += `- Negative: ${analysis.sentiment.negativeCount}\n`;
    }

    // Competitors
    if (analysis.competitorAnalysis?.competitors) {
      md += `\n## Competitor Comparison\n\n`;
      md += `| Brand | Mention Rate | Sentiment | Mindshare |\n`;
      md += `|-------|-------------|-----------|----------|\n`;
      for (const c of analysis.competitorAnalysis.competitors) {
        md += `| ${c.name} | ${c.mentionRate}% | ${c.sentiment.toFixed(3)} | ${c.mindshare}% |\n`;
      }
    }

    md += `\n---\n*Generated by Voyage GEO*\n`;

    const filePath = join(storage.getRunPath(data.runId), 'reports', 'report.md');
    await writeFile(filePath, md, 'utf-8');

    return md;
  }
}
